### ISSUE TITLE
关于原生ajax的错误提出

### ISSUE THREAD

**Issue by printjs** [GerryIsWarrior/ajax#3]
标题写错了，看着真的很碍眼

**Comment by GerryIsWarrior** [comment]
哪个标题 麻烦告诉一下  我来看一下

**Comment by printjs** [comment]
大哥。看你一下，你的readme.md

**Comment by GerryIsWarrior** [comment]
这句话有点歧义哦，是让我检查一下我的md文件，还是你要看我的md文件内容

**Comment by printjs** [comment]
肯定是你检查你的readme.md文件啊。我要看你的readme.md我可以直接看到的啊。

**Comment by GerryIsWarrior** [comment]
我是懵逼的，麻烦直接告诉我哪里错了，是哪个标题我改一下
