### ISSUE TITLE
跨域真的能实现？

### ISSUE THREAD

**Issue by wyhooo** [GerryIsWarrior/ajax#4]
粗略看了一下，代码里对跨域的区别貌似仅仅是参数里 crossDomain 为 true？

**Comment by GerryIsWarrior** [comment]
跨域是可以通过的，我在本地部署测试，是可以有用的。我现在抛出到外网访问测试一下。至于参数，本来是之前在xhr中手动设置请求头部的，但是一个朋友说，浏览器会自动加跨域请求头，然后我就去掉了，代码还没来得及更新，马上测试和更新

**Comment by GerryIsWarrior** [comment]
你可以使用我index.htnl中的方法测试，我抛到外网的接口是:http://zhong123893.oicp.net/api/weixin/ajaxT2/ ，post请求，参数分别为name和age。你可以自己测试下
