### ISSUE TITLE
[bug]：数据处理

### ISSUE THREAD

**Issue by ghost** [GerryIsWarrior/ajax#6]
```
tool.each(ajaxSetting.data,function(item,index){
     getParam +=(encodeURI(index)+"="+encodeURI(item)+"&")
 });
```
源码部分数据只是很浅的做了处理，比较深的数据你没有做递归，比如以下数据

```
{
     a : 213,
     b : [
           {c : 132}
      ]
}
```

**Comment by GerryIsWarrior** [comment]
恩恩，我做测试一下，然后再修正一下，感谢指出来


________________________________
发件人: Ayerss <notifications@github.com>
发送时间: 2017年4月21日 6:11
收件人: GerryIsWarrior/ajax
抄送: Subscribed
主题: [GerryIsWarrior/ajax] [bug]：数据处理 (#6)


tool.each(ajaxSetting.data,function(item,index){ getParam +=(encodeURI(index)+"="+encodeURI(item)+"&") });

源码部分数据只是很浅的做了处理，比较深的数据你没有做递归，比如以下数据

{
     a : 213,
     b : [
           {c : 132}
      ]
}


―

**Comment by GerryIsWarrior** [comment]
对于你提的这个问题，我查了关于ajax的设计方案level1和level2的规范。因为首先在中国当前的开发版本和环境中，ie10之前的版本 都必须兼容的，而在level1的方案中是这样说的：不能发送二进制文件（如图片、视频、音频等），只能发送纯文本数据。这个纯文本就是字符串。level2的方案应该已经支持了，我要做个全面的测试一下

**Comment by GerryIsWarrior** [comment]
对于level2的测试也做过了。下面是总结：
1.  在ajax方案中，只要不是发送二进制数据都是纯文本文件，所以后台接受的都是String类型的数据。你看到有些后台语言中能够将简单json转换为类的数据，是后台语言在request请求中做了一层简单的语法封装。但是对于足够复杂的json数据（数组中有json，json中有数组），这就必须自己处理
2. 处理这类数据的方案正常一般都是在前端传输的时候做处理的，否则后台接受到的数据就是[object object]这一种，因为后台语言明确上的基础数据类型都没有json这个类型。一般的解决方案就是将前端的复杂数据进行JSON序列，JSON.stringify（数据），比如你提供的数据就可以改成{ a : 213,b : JSON.stringify([ {c : 132} ])}，然后就可以通过ajax将数据发送到后台，后台接收到b这个数据进行反序列化映射成可读的class数据，在之前开发的项目中，我记得好像，我们就是这样前端封装，后端反序列化得到数据的。

**Comment by GerryIsWarrior** [comment]
忘了补充最根本的一点：对于json，本质上就是字符串，只是在前端转成对象了。
