### ISSUE TITLE
长轮询如何取消操作呢？

### ISSUE THREAD

**Issue by devmsg** [GerryIsWarrior/ajax#7]
hello 你好
我正在项目里使用你的ajax1.8的解决方案
有个问题不知道怎么解决
在我使用longPolling长轮询的时候，怎么进行取消操作呢，可否给个实例

![image](https://user-images.githubusercontent.com/15261658/44308469-2d72b600-a3e9-11e8-9f75-c9db1d90a84e.png)

万分感谢

**Comment by GerryIsWarrior** [comment]
![image](https://user-images.githubusercontent.com/10432318/44323433-9b1ff000-a484-11e8-9063-f6d8f8614ca6.png)
在回调成功之后有第二个参数，暴露内部变量，讲内部属性stop设置为true就好了。
例子：
ajax.longPolling('GET','./checkOrder',{id:1234},(data,that)=>{
    // 成功之后的取消
    that.stop = true
})
