### ISSUE TITLE
async:false无效

### ISSUE THREAD

**Issue by beausoft** [GerryIsWarrior/ajax#9]
即使设置async=false，也没用生效还是异步的

**Comment by GerryIsWarrior** [comment]
在同步下的注意规则：
      *   xhr.timeout必须为0
      *   xhr.withCredentials必须为 false
      *   xhr.responseType必须为""（注意置为"text"也不允许）

之前在配置该参数的时候赋值为默认值，但是在有些浏览器直接不允许赋值，否则会给你报错。该问题已解决。

同步请求在浏览器会给出警告：主线程上的同步XMLHttpRequest由于其对最终用户体验的不利影响而被弃用。 这个方法可能会被弃用不建议使用。且最新的API提供了promise和async await来处理异步。不过具体还需要结合自己需求使用。

问题已修复，浏览器已测试，感谢使用~（npm 需要重新安装一下，直接引入的话就拉一下最新的js文件就可以了）

**Comment by beausoft** [comment]
再同步的情况下，只能用get方式吗？

**Comment by GerryIsWarrior** [comment]
post也可以用的，不过需要用common方法设置async=
false，因为常用方法没有总结这个，官方API也不推荐使用的，所以没有提供常用方法
